# fly.toml file generated for reactivities-dummy on 2022-12-04T14:03:10+07:00

app = "reactivities-dummy"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "dummy/reactivities-dummy:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="CloudName"
  Cloudinary__ApiKey="ApiSecret"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"